export interface PriceTier {
  label: string
  price: number
  currency: string
  billingCycle: "monthly" | "yearly" | "quarterly" | "lifetime"
}

export interface SubscriptionTemplate {
  name: string
  logo: string
  category: string
  subcategory: string
  billingCycle: "monthly" | "yearly" | "quarterly" | "lifetime"
  renewalUrl: string
  tags: string[]
  commonPrices: PriceTier[]
  cancellationDifficulty?: "easy" | "medium" | "hard"
}

function logo(domain: string): string {
  return `https://logo.clearbit.com/${domain}`
}

export const SUBSCRIPTION_TEMPLATES: SubscriptionTemplate[] = [
  // ── AI Tools ──────────────────────────────────────────────────────────────
  {
    name: "ChatGPT Plus",
    logo: logo("openai.com"),
    category: "AI Tools",
    subcategory: "AI Chat",
    billingCycle: "monthly",
    renewalUrl: "https://chat.openai.com/account/billing",
    tags: ["chat", "ai"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Plus", price: 20, currency: "USD", billingCycle: "monthly" },
      { label: "Team (per seat)", price: 25, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Claude Pro",
    logo: logo("anthropic.com"),
    category: "AI Tools",
    subcategory: "AI Chat",
    billingCycle: "monthly",
    renewalUrl: "https://claude.ai/settings",
    tags: ["chat", "ai"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Pro", price: 20, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "GitHub Copilot",
    logo: logo("github.com"),
    category: "AI Tools",
    subcategory: "Code Generation",
    billingCycle: "monthly",
    renewalUrl: "https://github.com/settings/copilot",
    tags: ["code", "ai"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Individual", price: 10, currency: "USD", billingCycle: "monthly" },
      { label: "Individual (yearly)", price: 100, currency: "USD", billingCycle: "yearly" },
      { label: "Business (per seat)", price: 19, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Gemini Advanced",
    logo: logo("google.com"),
    category: "AI Tools",
    subcategory: "AI Chat",
    billingCycle: "monthly",
    renewalUrl: "https://one.google.com/about/plans",
    tags: ["chat", "ai"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Google One AI Premium", price: 19.99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Midjourney",
    logo: logo("midjourney.com"),
    category: "AI Tools",
    subcategory: "Image Generation",
    billingCycle: "monthly",
    renewalUrl: "https://www.midjourney.com/account",
    tags: ["image", "ai"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Basic", price: 10, currency: "USD", billingCycle: "monthly" },
      { label: "Standard", price: 30, currency: "USD", billingCycle: "monthly" },
      { label: "Pro", price: 60, currency: "USD", billingCycle: "monthly" },
      { label: "Mega", price: 120, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Perplexity Pro",
    logo: logo("perplexity.ai"),
    category: "AI Tools",
    subcategory: "AI Search",
    billingCycle: "monthly",
    renewalUrl: "https://www.perplexity.ai/settings/account",
    tags: ["search", "ai"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Pro", price: 20, currency: "USD", billingCycle: "monthly" },
      { label: "Pro (yearly)", price: 200, currency: "USD", billingCycle: "yearly" },
    ],
  },
  {
    name: "Jasper AI",
    logo: logo("jasper.ai"),
    category: "AI Tools",
    subcategory: "Content Writing",
    billingCycle: "monthly",
    renewalUrl: "https://app.jasper.ai/billing",
    tags: ["writing", "ai"],
    cancellationDifficulty: "medium",
    commonPrices: [
      { label: "Creator", price: 49, currency: "USD", billingCycle: "monthly" },
      { label: "Pro", price: 69, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Runway",
    logo: logo("runwayml.com"),
    category: "AI Tools",
    subcategory: "Video Generation",
    billingCycle: "monthly",
    renewalUrl: "https://app.runwayml.com/settings/billing",
    tags: ["video", "ai"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Standard", price: 15, currency: "USD", billingCycle: "monthly" },
      { label: "Pro", price: 35, currency: "USD", billingCycle: "monthly" },
      { label: "Unlimited", price: 95, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "ElevenLabs",
    logo: logo("elevenlabs.io"),
    category: "AI Tools",
    subcategory: "Voice AI",
    billingCycle: "monthly",
    renewalUrl: "https://elevenlabs.io/subscription",
    tags: ["voice", "ai"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Starter", price: 5, currency: "USD", billingCycle: "monthly" },
      { label: "Creator", price: 22, currency: "USD", billingCycle: "monthly" },
      { label: "Pro", price: 99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Cursor",
    logo: logo("cursor.com"),
    category: "AI Tools",
    subcategory: "Code Generation",
    billingCycle: "monthly",
    renewalUrl: "https://cursor.com/settings",
    tags: ["code", "ai"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Pro", price: 20, currency: "USD", billingCycle: "monthly" },
      { label: "Business (per seat)", price: 40, currency: "USD", billingCycle: "monthly" },
    ],
  },
  // ── Streaming ─────────────────────────────────────────────────────────────
  {
    name: "Netflix",
    logo: logo("netflix.com"),
    category: "Streaming",
    subcategory: "Video",
    billingCycle: "monthly",
    renewalUrl: "https://netflix.com/account",
    tags: ["video", "entertainment"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Standard with Ads", price: 7.99, currency: "USD", billingCycle: "monthly" },
      { label: "Standard", price: 15.49, currency: "USD", billingCycle: "monthly" },
      { label: "Premium", price: 22.99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Spotify",
    logo: logo("spotify.com"),
    category: "Streaming",
    subcategory: "Music",
    billingCycle: "monthly",
    renewalUrl: "https://www.spotify.com/account/subscription",
    tags: ["music", "audio"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Individual", price: 11.99, currency: "USD", billingCycle: "monthly" },
      { label: "Duo", price: 16.99, currency: "USD", billingCycle: "monthly" },
      { label: "Family", price: 19.99, currency: "USD", billingCycle: "monthly" },
      { label: "Student", price: 5.99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Disney+",
    logo: logo("disneyplus.com"),
    category: "Streaming",
    subcategory: "Video",
    billingCycle: "monthly",
    renewalUrl: "https://www.disneyplus.com/account/subscription",
    tags: ["video", "entertainment"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Basic (with Ads)", price: 7.99, currency: "USD", billingCycle: "monthly" },
      { label: "Premium", price: 13.99, currency: "USD", billingCycle: "monthly" },
      { label: "Premium (yearly)", price: 139.99, currency: "USD", billingCycle: "yearly" },
    ],
  },
  {
    name: "Hulu",
    logo: logo("hulu.com"),
    category: "Streaming",
    subcategory: "Video",
    billingCycle: "monthly",
    renewalUrl: "https://secure.hulu.com/account",
    tags: ["video", "entertainment"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "With Ads", price: 7.99, currency: "USD", billingCycle: "monthly" },
      { label: "No Ads", price: 17.99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "HBO Max",
    logo: logo("max.com"),
    category: "Streaming",
    subcategory: "Video",
    billingCycle: "monthly",
    renewalUrl: "https://www.max.com/account",
    tags: ["video", "entertainment"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "With Ads", price: 9.99, currency: "USD", billingCycle: "monthly" },
      { label: "Ad-Free", price: 15.99, currency: "USD", billingCycle: "monthly" },
      { label: "Ultimate", price: 19.99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Apple TV+",
    logo: logo("apple.com"),
    category: "Streaming",
    subcategory: "Video",
    billingCycle: "monthly",
    renewalUrl: "https://tv.apple.com/settings",
    tags: ["video", "entertainment"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Individual", price: 9.99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "YouTube Premium",
    logo: logo("youtube.com"),
    category: "Streaming",
    subcategory: "Video",
    billingCycle: "monthly",
    renewalUrl: "https://www.youtube.com/paid_memberships",
    tags: ["video", "entertainment"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Individual", price: 13.99, currency: "USD", billingCycle: "monthly" },
      { label: "Family", price: 22.99, currency: "USD", billingCycle: "monthly" },
      { label: "Student", price: 7.99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Apple Music",
    logo: logo("apple.com"),
    category: "Streaming",
    subcategory: "Music",
    billingCycle: "monthly",
    renewalUrl: "https://music.apple.com/account",
    tags: ["music", "audio"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Individual", price: 10.99, currency: "USD", billingCycle: "monthly" },
      { label: "Family", price: 16.99, currency: "USD", billingCycle: "monthly" },
      { label: "Student", price: 5.99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Tidal",
    logo: logo("tidal.com"),
    category: "Streaming",
    subcategory: "Music",
    billingCycle: "monthly",
    renewalUrl: "https://account.tidal.com",
    tags: ["music", "audio"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Individual", price: 10.99, currency: "USD", billingCycle: "monthly" },
      { label: "HiFi Plus", price: 19.99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Paramount+",
    logo: logo("paramountplus.com"),
    category: "Streaming",
    subcategory: "Video",
    billingCycle: "monthly",
    renewalUrl: "https://www.paramountplus.com/account",
    tags: ["video", "entertainment"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Essential", price: 5.99, currency: "USD", billingCycle: "monthly" },
      { label: "With SHOWTIME", price: 11.99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Peacock",
    logo: logo("peacocktv.com"),
    category: "Streaming",
    subcategory: "Video",
    billingCycle: "monthly",
    renewalUrl: "https://www.peacocktv.com/account",
    tags: ["video", "entertainment"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Premium", price: 7.99, currency: "USD", billingCycle: "monthly" },
      { label: "Premium Plus", price: 13.99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Crunchyroll",
    logo: logo("crunchyroll.com"),
    category: "Streaming",
    subcategory: "Anime",
    billingCycle: "monthly",
    renewalUrl: "https://www.crunchyroll.com/account",
    tags: ["anime", "entertainment"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Fan", price: 7.99, currency: "USD", billingCycle: "monthly" },
      { label: "Mega Fan", price: 9.99, currency: "USD", billingCycle: "monthly" },
      { label: "Ultimate Fan", price: 14.99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Audible",
    logo: logo("audible.com"),
    category: "Streaming",
    subcategory: "Audiobooks",
    billingCycle: "monthly",
    renewalUrl: "https://www.audible.com/account/manage-membership",
    tags: ["audiobooks", "audio"],
    cancellationDifficulty: "medium",
    commonPrices: [
      { label: "Plus", price: 7.95, currency: "USD", billingCycle: "monthly" },
      { label: "Premium Plus", price: 14.95, currency: "USD", billingCycle: "monthly" },
    ],
  },
  // ── Productivity ──────────────────────────────────────────────────────────
  {
    name: "Notion",
    logo: logo("notion.so"),
    category: "Productivity",
    subcategory: "Notes & Docs",
    billingCycle: "monthly",
    renewalUrl: "https://www.notion.so/profile/billing",
    tags: ["productivity", "notes"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Plus", price: 10, currency: "USD", billingCycle: "monthly" },
      { label: "Business", price: 15, currency: "USD", billingCycle: "monthly" },
      { label: "Plus (yearly)", price: 96, currency: "USD", billingCycle: "yearly" },
    ],
  },
  {
    name: "Microsoft 365",
    logo: logo("microsoft.com"),
    category: "Productivity",
    subcategory: "Office Suite",
    billingCycle: "monthly",
    renewalUrl: "https://account.microsoft.com/services",
    tags: ["productivity", "office"],
    cancellationDifficulty: "medium",
    commonPrices: [
      { label: "Personal", price: 6.99, currency: "USD", billingCycle: "monthly" },
      { label: "Family", price: 9.99, currency: "USD", billingCycle: "monthly" },
      { label: "Personal (yearly)", price: 69.99, currency: "USD", billingCycle: "yearly" },
    ],
  },
  {
    name: "Google Workspace",
    logo: logo("workspace.google.com"),
    category: "Productivity",
    subcategory: "Office Suite",
    billingCycle: "monthly",
    renewalUrl: "https://admin.google.com/ac/billing",
    tags: ["productivity", "office"],
    cancellationDifficulty: "medium",
    commonPrices: [
      { label: "Business Starter", price: 6, currency: "USD", billingCycle: "monthly" },
      { label: "Business Standard", price: 12, currency: "USD", billingCycle: "monthly" },
      { label: "Business Plus", price: 18, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Dropbox",
    logo: logo("dropbox.com"),
    category: "Productivity",
    subcategory: "Cloud Storage",
    billingCycle: "monthly",
    renewalUrl: "https://www.dropbox.com/account/plan",
    tags: ["storage", "cloud"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Plus", price: 11.99, currency: "USD", billingCycle: "monthly" },
      { label: "Professional", price: 19.99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Zoom",
    logo: logo("zoom.us"),
    category: "Productivity",
    subcategory: "Video Conferencing",
    billingCycle: "monthly",
    renewalUrl: "https://zoom.us/billing",
    tags: ["video", "meetings"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Pro", price: 14.99, currency: "USD", billingCycle: "monthly" },
      { label: "Business", price: 19.99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Slack",
    logo: logo("slack.com"),
    category: "Productivity",
    subcategory: "Team Communication",
    billingCycle: "monthly",
    renewalUrl: "https://slack.com/account/billing",
    tags: ["communication", "team"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Pro", price: 7.25, currency: "USD", billingCycle: "monthly" },
      { label: "Business+", price: 12.50, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Todoist",
    logo: logo("todoist.com"),
    category: "Productivity",
    subcategory: "Task Management",
    billingCycle: "monthly",
    renewalUrl: "https://todoist.com/app/settings/subscription",
    tags: ["productivity", "tasks"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Pro", price: 4, currency: "USD", billingCycle: "monthly" },
      { label: "Business", price: 6, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Evernote",
    logo: logo("evernote.com"),
    category: "Productivity",
    subcategory: "Notes & Docs",
    billingCycle: "monthly",
    renewalUrl: "https://www.evernote.com/Settings.action",
    tags: ["productivity", "notes"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Personal", price: 10.83, currency: "USD", billingCycle: "monthly" },
      { label: "Professional", price: 14.17, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Asana",
    logo: logo("asana.com"),
    category: "Productivity",
    subcategory: "Project Management",
    billingCycle: "monthly",
    renewalUrl: "https://app.asana.com/-/admin_console/billing",
    tags: ["productivity", "project-management"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Starter", price: 10.99, currency: "USD", billingCycle: "monthly" },
      { label: "Advanced", price: 24.99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Monday.com",
    logo: logo("monday.com"),
    category: "Productivity",
    subcategory: "Project Management",
    billingCycle: "monthly",
    renewalUrl: "https://auth.monday.com/billing",
    tags: ["productivity", "project-management"],
    cancellationDifficulty: "medium",
    commonPrices: [
      { label: "Basic (per seat)", price: 9, currency: "USD", billingCycle: "monthly" },
      { label: "Standard (per seat)", price: 12, currency: "USD", billingCycle: "monthly" },
      { label: "Pro (per seat)", price: 19, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Linear",
    logo: logo("linear.app"),
    category: "Productivity",
    subcategory: "Project Management",
    billingCycle: "monthly",
    renewalUrl: "https://linear.app/settings/billing",
    tags: ["productivity", "project-management"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Business (per seat)", price: 8, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Airtable",
    logo: logo("airtable.com"),
    category: "Productivity",
    subcategory: "Database",
    billingCycle: "monthly",
    renewalUrl: "https://airtable.com/account",
    tags: ["productivity", "database"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Team", price: 20, currency: "USD", billingCycle: "monthly" },
      { label: "Business", price: 45, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "1Password",
    logo: logo("1password.com"),
    category: "Productivity",
    subcategory: "Password Manager",
    billingCycle: "yearly",
    renewalUrl: "https://my.1password.com/billing",
    tags: ["security", "passwords"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Individual", price: 2.99, currency: "USD", billingCycle: "monthly" },
      { label: "Families", price: 4.99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "LastPass",
    logo: logo("lastpass.com"),
    category: "Productivity",
    subcategory: "Password Manager",
    billingCycle: "yearly",
    renewalUrl: "https://lastpass.com/account",
    tags: ["security", "passwords"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Premium", price: 3, currency: "USD", billingCycle: "monthly" },
      { label: "Families", price: 4, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Grammarly",
    logo: logo("grammarly.com"),
    category: "Productivity",
    subcategory: "Writing Assistant",
    billingCycle: "monthly",
    renewalUrl: "https://account.grammarly.com/subscription",
    tags: ["writing", "productivity"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Premium", price: 12, currency: "USD", billingCycle: "monthly" },
      { label: "Business (per seat)", price: 15, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Loom",
    logo: logo("loom.com"),
    category: "Productivity",
    subcategory: "Video Messaging",
    billingCycle: "monthly",
    renewalUrl: "https://www.loom.com/settings/billing",
    tags: ["video", "communication"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Business (per seat)", price: 12.50, currency: "USD", billingCycle: "monthly" },
    ],
  },
  // ── Design ────────────────────────────────────────────────────────────────
  {
    name: "Adobe Creative Cloud",
    logo: logo("adobe.com"),
    category: "Design",
    subcategory: "Design Suite",
    billingCycle: "monthly",
    renewalUrl: "https://account.adobe.com/plans",
    tags: ["design", "creative"],
    cancellationDifficulty: "hard",
    commonPrices: [
      { label: "Photography", price: 9.99, currency: "USD", billingCycle: "monthly" },
      { label: "Single App", price: 29.99, currency: "USD", billingCycle: "monthly" },
      { label: "All Apps", price: 54.99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Figma",
    logo: logo("figma.com"),
    category: "Design",
    subcategory: "UI/UX Design",
    billingCycle: "monthly",
    renewalUrl: "https://www.figma.com/settings/billing",
    tags: ["design", "ui"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Professional (per seat)", price: 12, currency: "USD", billingCycle: "monthly" },
      { label: "Organization (per seat)", price: 45, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Canva Pro",
    logo: logo("canva.com"),
    category: "Design",
    subcategory: "Graphic Design",
    billingCycle: "monthly",
    renewalUrl: "https://www.canva.com/settings/billing",
    tags: ["design", "graphics"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Pro", price: 14.99, currency: "USD", billingCycle: "monthly" },
      { label: "Teams (per seat)", price: 10, currency: "USD", billingCycle: "monthly" },
      { label: "Pro (yearly)", price: 119.99, currency: "USD", billingCycle: "yearly" },
    ],
  },
  {
    name: "Sketch",
    logo: logo("sketch.com"),
    category: "Design",
    subcategory: "UI/UX Design",
    billingCycle: "yearly",
    renewalUrl: "https://www.sketch.com/account",
    tags: ["design", "ui"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Standard (per editor)", price: 9, currency: "USD", billingCycle: "monthly" },
      { label: "Business (per editor)", price: 20, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Framer",
    logo: logo("framer.com"),
    category: "Design",
    subcategory: "Web Design",
    billingCycle: "monthly",
    renewalUrl: "https://www.framer.com/settings/billing",
    tags: ["design", "web"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Mini", price: 5, currency: "USD", billingCycle: "monthly" },
      { label: "Basic", price: 15, currency: "USD", billingCycle: "monthly" },
      { label: "Pro", price: 30, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Webflow",
    logo: logo("webflow.com"),
    category: "Design",
    subcategory: "Web Design",
    billingCycle: "monthly",
    renewalUrl: "https://webflow.com/dashboard/billing",
    tags: ["design", "web"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Basic", price: 14, currency: "USD", billingCycle: "monthly" },
      { label: "CMS", price: 23, currency: "USD", billingCycle: "monthly" },
      { label: "Business", price: 39, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Procreate",
    logo: logo("procreate.art"),
    category: "Design",
    subcategory: "Digital Art",
    billingCycle: "lifetime",
    renewalUrl: "https://procreate.art",
    tags: ["design", "art"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "One-time purchase", price: 12.99, currency: "USD", billingCycle: "lifetime" },
    ],
  },
  // ── Development ───────────────────────────────────────────────────────────
  {
    name: "GitHub Pro",
    logo: logo("github.com"),
    category: "Development",
    subcategory: "Version Control",
    billingCycle: "monthly",
    renewalUrl: "https://github.com/settings/billing",
    tags: ["development", "code"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Pro", price: 4, currency: "USD", billingCycle: "monthly" },
      { label: "Team", price: 4, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Vercel Pro",
    logo: logo("vercel.com"),
    category: "Development",
    subcategory: "Hosting",
    billingCycle: "monthly",
    renewalUrl: "https://vercel.com/account/billing",
    tags: ["development", "hosting"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Pro", price: 20, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Netlify",
    logo: logo("netlify.com"),
    category: "Development",
    subcategory: "Hosting",
    billingCycle: "monthly",
    renewalUrl: "https://app.netlify.com/billing",
    tags: ["development", "hosting"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Pro", price: 19, currency: "USD", billingCycle: "monthly" },
      { label: "Business", price: 99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Heroku",
    logo: logo("heroku.com"),
    category: "Development",
    subcategory: "Hosting",
    billingCycle: "monthly",
    renewalUrl: "https://dashboard.heroku.com/account/billing",
    tags: ["development", "hosting"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Eco Dynos", price: 5, currency: "USD", billingCycle: "monthly" },
      { label: "Basic Dynos", price: 7, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Supabase",
    logo: logo("supabase.com"),
    category: "Development",
    subcategory: "Backend",
    billingCycle: "monthly",
    renewalUrl: "https://supabase.com/dashboard/account/billing",
    tags: ["development", "database"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Pro", price: 25, currency: "USD", billingCycle: "monthly" },
      { label: "Team", price: 599, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "PlanetScale",
    logo: logo("planetscale.com"),
    category: "Development",
    subcategory: "Database",
    billingCycle: "monthly",
    renewalUrl: "https://app.planetscale.com/settings/billing",
    tags: ["development", "database"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Scaler", price: 29, currency: "USD", billingCycle: "monthly" },
      { label: "Scaler Pro", price: 39, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Sentry",
    logo: logo("sentry.io"),
    category: "Development",
    subcategory: "Monitoring",
    billingCycle: "monthly",
    renewalUrl: "https://sentry.io/settings/billing",
    tags: ["development", "monitoring"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Team", price: 26, currency: "USD", billingCycle: "monthly" },
      { label: "Business", price: 80, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Datadog",
    logo: logo("datadoghq.com"),
    category: "Development",
    subcategory: "Monitoring",
    billingCycle: "monthly",
    renewalUrl: "https://app.datadoghq.com/billing",
    tags: ["development", "monitoring"],
    cancellationDifficulty: "medium",
    commonPrices: [
      { label: "Pro (per host)", price: 15, currency: "USD", billingCycle: "monthly" },
      { label: "Enterprise (per host)", price: 23, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Postman",
    logo: logo("postman.com"),
    category: "Development",
    subcategory: "API Tools",
    billingCycle: "monthly",
    renewalUrl: "https://go.postman.co/billing",
    tags: ["development", "api"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Basic (per user)", price: 14, currency: "USD", billingCycle: "monthly" },
      { label: "Professional (per user)", price: 29, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Cloudflare",
    logo: logo("cloudflare.com"),
    category: "Development",
    subcategory: "CDN & Security",
    billingCycle: "monthly",
    renewalUrl: "https://dash.cloudflare.com/billing",
    tags: ["development", "cdn"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Pro", price: 20, currency: "USD", billingCycle: "monthly" },
      { label: "Business", price: 200, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Render",
    logo: logo("render.com"),
    category: "Development",
    subcategory: "Hosting",
    billingCycle: "monthly",
    renewalUrl: "https://dashboard.render.com/billing",
    tags: ["development", "hosting"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Starter", price: 7, currency: "USD", billingCycle: "monthly" },
      { label: "Standard", price: 25, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Railway",
    logo: logo("railway.app"),
    category: "Development",
    subcategory: "Hosting",
    billingCycle: "monthly",
    renewalUrl: "https://railway.app/account/billing",
    tags: ["development", "hosting"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Hobby", price: 5, currency: "USD", billingCycle: "monthly" },
      { label: "Pro", price: 20, currency: "USD", billingCycle: "monthly" },
    ],
  },
  // ── Finance ───────────────────────────────────────────────────────────────
  {
    name: "QuickBooks",
    logo: logo("quickbooks.intuit.com"),
    category: "Finance",
    subcategory: "Accounting",
    billingCycle: "monthly",
    renewalUrl: "https://accounts.intuit.com/billing",
    tags: ["finance", "accounting"],
    cancellationDifficulty: "medium",
    commonPrices: [
      { label: "Simple Start", price: 30, currency: "USD", billingCycle: "monthly" },
      { label: "Essentials", price: 60, currency: "USD", billingCycle: "monthly" },
      { label: "Plus", price: 90, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "FreshBooks",
    logo: logo("freshbooks.com"),
    category: "Finance",
    subcategory: "Accounting",
    billingCycle: "monthly",
    renewalUrl: "https://my.freshbooks.com/settings/billing",
    tags: ["finance", "accounting"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Lite", price: 17, currency: "USD", billingCycle: "monthly" },
      { label: "Plus", price: 30, currency: "USD", billingCycle: "monthly" },
      { label: "Premium", price: 55, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Xero",
    logo: logo("xero.com"),
    category: "Finance",
    subcategory: "Accounting",
    billingCycle: "monthly",
    renewalUrl: "https://www.xero.com/us/accounting-software/pricing",
    tags: ["finance", "accounting"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Starter", price: 29, currency: "USD", billingCycle: "monthly" },
      { label: "Standard", price: 46, currency: "USD", billingCycle: "monthly" },
      { label: "Premium", price: 62, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "YNAB",
    logo: logo("ynab.com"),
    category: "Finance",
    subcategory: "Budgeting",
    billingCycle: "yearly",
    renewalUrl: "https://app.ynab.com/settings/subscription",
    tags: ["finance", "budgeting"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Annual", price: 99, currency: "USD", billingCycle: "yearly" },
      { label: "Monthly", price: 14.99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  // ── Health & Fitness ──────────────────────────────────────────────────────
  {
    name: "Peloton",
    logo: logo("onepeloton.com"),
    category: "Health",
    subcategory: "Fitness",
    billingCycle: "monthly",
    renewalUrl: "https://members.onepeloton.com/profile/billing",
    tags: ["health", "fitness"],
    cancellationDifficulty: "medium",
    commonPrices: [
      { label: "App One", price: 12.99, currency: "USD", billingCycle: "monthly" },
      { label: "App+", price: 24, currency: "USD", billingCycle: "monthly" },
      { label: "All-Access", price: 44, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Headspace",
    logo: logo("headspace.com"),
    category: "Health",
    subcategory: "Meditation",
    billingCycle: "yearly",
    renewalUrl: "https://www.headspace.com/account",
    tags: ["health", "meditation"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Monthly", price: 12.99, currency: "USD", billingCycle: "monthly" },
      { label: "Annual", price: 69.99, currency: "USD", billingCycle: "yearly" },
    ],
  },
  {
    name: "Calm",
    logo: logo("calm.com"),
    category: "Health",
    subcategory: "Meditation",
    billingCycle: "yearly",
    renewalUrl: "https://www.calm.com/account",
    tags: ["health", "meditation"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Monthly", price: 14.99, currency: "USD", billingCycle: "monthly" },
      { label: "Annual", price: 69.99, currency: "USD", billingCycle: "yearly" },
    ],
  },
  {
    name: "Noom",
    logo: logo("noom.com"),
    category: "Health",
    subcategory: "Weight Loss",
    billingCycle: "monthly",
    renewalUrl: "https://web.noom.com/settings/billing",
    tags: ["health", "fitness"],
    cancellationDifficulty: "hard",
    commonPrices: [
      { label: "Monthly", price: 70, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "MyFitnessPal",
    logo: logo("myfitnesspal.com"),
    category: "Health",
    subcategory: "Fitness Tracking",
    billingCycle: "monthly",
    renewalUrl: "https://www.myfitnesspal.com/account/subscription",
    tags: ["health", "fitness"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Premium", price: 9.99, currency: "USD", billingCycle: "monthly" },
      { label: "Premium (yearly)", price: 49.99, currency: "USD", billingCycle: "yearly" },
    ],
  },
  // ── Gaming ────────────────────────────────────────────────────────────────
  {
    name: "PlayStation Plus",
    logo: logo("playstation.com"),
    category: "Gaming",
    subcategory: "Console",
    billingCycle: "monthly",
    renewalUrl: "https://www.playstation.com/en-us/ps-plus",
    tags: ["gaming", "entertainment"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Essential", price: 9.99, currency: "USD", billingCycle: "monthly" },
      { label: "Extra", price: 14.99, currency: "USD", billingCycle: "monthly" },
      { label: "Premium", price: 17.99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Xbox Game Pass",
    logo: logo("xbox.com"),
    category: "Gaming",
    subcategory: "Console",
    billingCycle: "monthly",
    renewalUrl: "https://www.xbox.com/en-US/xbox-game-pass",
    tags: ["gaming", "entertainment"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Core", price: 9.99, currency: "USD", billingCycle: "monthly" },
      { label: "PC Game Pass", price: 11.99, currency: "USD", billingCycle: "monthly" },
      { label: "Ultimate", price: 16.99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Nintendo Switch Online",
    logo: logo("nintendo.com"),
    category: "Gaming",
    subcategory: "Console",
    billingCycle: "yearly",
    renewalUrl: "https://accounts.nintendo.com/profile/edit/membership",
    tags: ["gaming", "entertainment"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Individual", price: 3.99, currency: "USD", billingCycle: "monthly" },
      { label: "Family", price: 34.99, currency: "USD", billingCycle: "yearly" },
      { label: "Expansion Pack", price: 49.99, currency: "USD", billingCycle: "yearly" },
    ],
  },
  {
    name: "EA Play",
    logo: logo("ea.com"),
    category: "Gaming",
    subcategory: "PC/Console",
    billingCycle: "monthly",
    renewalUrl: "https://www.ea.com/ea-play",
    tags: ["gaming", "entertainment"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "EA Play", price: 4.99, currency: "USD", billingCycle: "monthly" },
      { label: "EA Play Pro", price: 14.99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Twitch Turbo",
    logo: logo("twitch.tv"),
    category: "Gaming",
    subcategory: "Streaming",
    billingCycle: "monthly",
    renewalUrl: "https://www.twitch.tv/turbo",
    tags: ["gaming", "streaming"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Turbo", price: 8.99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  // ── Education ─────────────────────────────────────────────────────────────
  {
    name: "Duolingo Plus",
    logo: logo("duolingo.com"),
    category: "Education",
    subcategory: "Language Learning",
    billingCycle: "monthly",
    renewalUrl: "https://www.duolingo.com/settings/subscription",
    tags: ["education", "language"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Super", price: 6.99, currency: "USD", billingCycle: "monthly" },
      { label: "Super (yearly)", price: 83.99, currency: "USD", billingCycle: "yearly" },
    ],
  },
  {
    name: "Coursera Plus",
    logo: logo("coursera.org"),
    category: "Education",
    subcategory: "Online Courses",
    billingCycle: "monthly",
    renewalUrl: "https://www.coursera.org/account-profile",
    tags: ["education", "courses"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Monthly", price: 59, currency: "USD", billingCycle: "monthly" },
      { label: "Annual", price: 399, currency: "USD", billingCycle: "yearly" },
    ],
  },
  {
    name: "MasterClass",
    logo: logo("masterclass.com"),
    category: "Education",
    subcategory: "Online Courses",
    billingCycle: "yearly",
    renewalUrl: "https://www.masterclass.com/account/billing",
    tags: ["education", "courses"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Individual", price: 10, currency: "USD", billingCycle: "monthly" },
      { label: "Duo", price: 15, currency: "USD", billingCycle: "monthly" },
      { label: "Family", price: 20, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "LinkedIn Learning",
    logo: logo("linkedin.com"),
    category: "Education",
    subcategory: "Professional Development",
    billingCycle: "monthly",
    renewalUrl: "https://www.linkedin.com/learning/settings/billing",
    tags: ["education", "professional"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Monthly", price: 39.99, currency: "USD", billingCycle: "monthly" },
      { label: "Annual", price: 239.88, currency: "USD", billingCycle: "yearly" },
    ],
  },
  {
    name: "Skillshare",
    logo: logo("skillshare.com"),
    category: "Education",
    subcategory: "Online Courses",
    billingCycle: "yearly",
    renewalUrl: "https://www.skillshare.com/settings/membership",
    tags: ["education", "courses"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Monthly", price: 32, currency: "USD", billingCycle: "monthly" },
      { label: "Annual", price: 168, currency: "USD", billingCycle: "yearly" },
    ],
  },
  // ── Business & Marketing ──────────────────────────────────────────────────
  {
    name: "HubSpot",
    logo: logo("hubspot.com"),
    category: "Business",
    subcategory: "CRM & Marketing",
    billingCycle: "monthly",
    renewalUrl: "https://app.hubspot.com/billing",
    tags: ["business", "crm"],
    cancellationDifficulty: "medium",
    commonPrices: [
      { label: "Starter", price: 20, currency: "USD", billingCycle: "monthly" },
      { label: "Professional", price: 890, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Mailchimp",
    logo: logo("mailchimp.com"),
    category: "Business",
    subcategory: "Email Marketing",
    billingCycle: "monthly",
    renewalUrl: "https://admin.mailchimp.com/account/billing",
    tags: ["business", "email"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Essentials", price: 13, currency: "USD", billingCycle: "monthly" },
      { label: "Standard", price: 20, currency: "USD", billingCycle: "monthly" },
      { label: "Premium", price: 350, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Intercom",
    logo: logo("intercom.com"),
    category: "Business",
    subcategory: "Customer Support",
    billingCycle: "monthly",
    renewalUrl: "https://app.intercom.com/a/billing",
    tags: ["business", "support"],
    cancellationDifficulty: "medium",
    commonPrices: [
      { label: "Essential", price: 39, currency: "USD", billingCycle: "monthly" },
      { label: "Advanced", price: 99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Zapier",
    logo: logo("zapier.com"),
    category: "Business",
    subcategory: "Automation",
    billingCycle: "monthly",
    renewalUrl: "https://zapier.com/app/billing",
    tags: ["business", "automation"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Starter", price: 19.99, currency: "USD", billingCycle: "monthly" },
      { label: "Professional", price: 49, currency: "USD", billingCycle: "monthly" },
      { label: "Team", price: 69, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Typeform",
    logo: logo("typeform.com"),
    category: "Business",
    subcategory: "Forms & Surveys",
    billingCycle: "monthly",
    renewalUrl: "https://admin.typeform.com/account/billing",
    tags: ["business", "forms"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Basic", price: 25, currency: "USD", billingCycle: "monthly" },
      { label: "Plus", price: 50, currency: "USD", billingCycle: "monthly" },
      { label: "Business", price: 83, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Semrush",
    logo: logo("semrush.com"),
    category: "Business",
    subcategory: "SEO",
    billingCycle: "monthly",
    renewalUrl: "https://www.semrush.com/billing",
    tags: ["business", "seo"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Pro", price: 129.95, currency: "USD", billingCycle: "monthly" },
      { label: "Guru", price: 249.95, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Ahrefs",
    logo: logo("ahrefs.com"),
    category: "Business",
    subcategory: "SEO",
    billingCycle: "monthly",
    renewalUrl: "https://app.ahrefs.com/billing",
    tags: ["business", "seo"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Lite", price: 99, currency: "USD", billingCycle: "monthly" },
      { label: "Standard", price: 199, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Shopify",
    logo: logo("shopify.com"),
    category: "Business",
    subcategory: "E-commerce",
    billingCycle: "monthly",
    renewalUrl: "https://www.shopify.com/admin/settings/billing",
    tags: ["business", "ecommerce"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Basic", price: 29, currency: "USD", billingCycle: "monthly" },
      { label: "Shopify", price: 79, currency: "USD", billingCycle: "monthly" },
      { label: "Advanced", price: 299, currency: "USD", billingCycle: "monthly" },
    ],
  },
  // ── Security & VPN ────────────────────────────────────────────────────────
  {
    name: "NordVPN",
    logo: logo("nordvpn.com"),
    category: "Productivity",
    subcategory: "VPN",
    billingCycle: "yearly",
    renewalUrl: "https://my.nordaccount.com/billing",
    tags: ["security", "vpn"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Basic (monthly)", price: 12.99, currency: "USD", billingCycle: "monthly" },
      { label: "Basic (yearly)", price: 59.88, currency: "USD", billingCycle: "yearly" },
      { label: "Plus (yearly)", price: 83.88, currency: "USD", billingCycle: "yearly" },
    ],
  },
  {
    name: "ExpressVPN",
    logo: logo("expressvpn.com"),
    category: "Productivity",
    subcategory: "VPN",
    billingCycle: "yearly",
    renewalUrl: "https://www.expressvpn.com/subscriptions",
    tags: ["security", "vpn"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Monthly", price: 12.95, currency: "USD", billingCycle: "monthly" },
      { label: "Annual", price: 99.95, currency: "USD", billingCycle: "yearly" },
    ],
  },
  // ── Storage ───────────────────────────────────────────────────────────────
  {
    name: "iCloud+",
    logo: logo("apple.com"),
    category: "Productivity",
    subcategory: "Cloud Storage",
    billingCycle: "monthly",
    renewalUrl: "https://appleid.apple.com/account/manage",
    tags: ["storage", "cloud"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "50 GB", price: 0.99, currency: "USD", billingCycle: "monthly" },
      { label: "200 GB", price: 2.99, currency: "USD", billingCycle: "monthly" },
      { label: "2 TB", price: 9.99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Google One",
    logo: logo("one.google.com"),
    category: "Productivity",
    subcategory: "Cloud Storage",
    billingCycle: "monthly",
    renewalUrl: "https://one.google.com/storage",
    tags: ["storage", "cloud"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "100 GB", price: 1.99, currency: "USD", billingCycle: "monthly" },
      { label: "200 GB", price: 2.99, currency: "USD", billingCycle: "monthly" },
      { label: "2 TB", price: 9.99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  // ── Communication ─────────────────────────────────────────────────────────
  {
    name: "Discord Nitro",
    logo: logo("discord.com"),
    category: "Productivity",
    subcategory: "Communication",
    billingCycle: "monthly",
    renewalUrl: "https://discord.com/settings/subscriptions",
    tags: ["communication", "gaming"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Nitro Basic", price: 2.99, currency: "USD", billingCycle: "monthly" },
      { label: "Nitro", price: 9.99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Telegram Premium",
    logo: logo("telegram.org"),
    category: "Productivity",
    subcategory: "Communication",
    billingCycle: "monthly",
    renewalUrl: "https://t.me/premiumbot",
    tags: ["communication"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Premium", price: 4.99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  // ── News & Reading ────────────────────────────────────────────────────────
  {
    name: "Medium",
    logo: logo("medium.com"),
    category: "Education",
    subcategory: "Reading",
    billingCycle: "monthly",
    renewalUrl: "https://medium.com/me/membership",
    tags: ["reading", "news"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Member", price: 5, currency: "USD", billingCycle: "monthly" },
      { label: "Member (yearly)", price: 50, currency: "USD", billingCycle: "yearly" },
    ],
  },
  {
    name: "Substack",
    logo: logo("substack.com"),
    category: "Education",
    subcategory: "Newsletter",
    billingCycle: "monthly",
    renewalUrl: "https://substack.com/account/billing",
    tags: ["reading", "newsletter"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Varies by publication", price: 5, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "The New York Times",
    logo: logo("nytimes.com"),
    category: "Education",
    subcategory: "News",
    billingCycle: "monthly",
    renewalUrl: "https://myaccount.nytimes.com/seg/subscription",
    tags: ["news", "reading"],
    cancellationDifficulty: "hard",
    commonPrices: [
      { label: "Basic Digital", price: 17, currency: "USD", billingCycle: "monthly" },
      { label: "All Access", price: 25, currency: "USD", billingCycle: "monthly" },
    ],
  },
  // ── Creative & Music Production ───────────────────────────────────────────
  {
    name: "Splice",
    logo: logo("splice.com"),
    category: "Design",
    subcategory: "Music Production",
    billingCycle: "monthly",
    renewalUrl: "https://splice.com/account/billing",
    tags: ["music", "creative"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Creator", price: 7.99, currency: "USD", billingCycle: "monthly" },
      { label: "Sounds", price: 13.99, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Epidemic Sound",
    logo: logo("epidemicsound.com"),
    category: "Design",
    subcategory: "Music Licensing",
    billingCycle: "monthly",
    renewalUrl: "https://www.epidemicsound.com/account/billing",
    tags: ["music", "creative"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Personal", price: 11, currency: "USD", billingCycle: "monthly" },
      { label: "Commercial", price: 23, currency: "USD", billingCycle: "monthly" },
    ],
  },
  // ── Analytics ─────────────────────────────────────────────────────────────
  {
    name: "Mixpanel",
    logo: logo("mixpanel.com"),
    category: "Business",
    subcategory: "Analytics",
    billingCycle: "monthly",
    renewalUrl: "https://mixpanel.com/settings/billing",
    tags: ["analytics", "business"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Growth", price: 28, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Amplitude",
    logo: logo("amplitude.com"),
    category: "Business",
    subcategory: "Analytics",
    billingCycle: "monthly",
    renewalUrl: "https://app.amplitude.com/settings/billing",
    tags: ["analytics", "business"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Plus", price: 61, currency: "USD", billingCycle: "monthly" },
    ],
  },
  {
    name: "Hotjar",
    logo: logo("hotjar.com"),
    category: "Business",
    subcategory: "Analytics",
    billingCycle: "monthly",
    renewalUrl: "https://insights.hotjar.com/settings/billing",
    tags: ["analytics", "ux"],
    cancellationDifficulty: "easy",
    commonPrices: [
      { label: "Plus", price: 32, currency: "USD", billingCycle: "monthly" },
      { label: "Business", price: 80, currency: "USD", billingCycle: "monthly" },
    ],
  },
]

export const TEMPLATE_CATEGORIES = [
  "All",
  "AI Tools",
  "Streaming",
  "Productivity",
  "Design",
  "Development",
  "Finance",
  "Health",
  "Gaming",
  "Education",
  "Business",
]

export function searchTemplates(query: string, category: string): SubscriptionTemplate[] {
  return SUBSCRIPTION_TEMPLATES.filter((t) => {
    const matchesCategory = category === "All" || t.category === category
    if (!query) return matchesCategory
    const q = query.toLowerCase()
    return matchesCategory && (
      t.name.toLowerCase().includes(q) ||
      t.category.toLowerCase().includes(q) ||
      t.subcategory.toLowerCase().includes(q) ||
      t.tags.some((tag) => tag.includes(q))
    )
  })
}
